### ISSUE TITLE
Add Int.range

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#15]
This issue aims to add the `Int.range` function to the base library.

* Uses the same mechanism as `Nat.range`
* Documented under `range.doc` and linked.
* `Author` and `License` metadata linked :man_shrugging: 
*Unit tested with positive and negative scenarios.

## Code review
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.Int https://github.com/pete-ts/base:.base.Int
  
  Added definitions:
  
     range                              : Int -> Int -> [Int] (+1 metadata)
     range.doc                          : Doc
     range.examples.invalid.descFromNeg : [Int]
     range.examples.invalid.descFromPos : [Int]
     range.examples.valid.ascFromNeg    : [Int]
     range.examples.valid.ascFromNeg2   : [Int]
     range.examples.valid.ascFromPos    : [Int]
     range.tests.invalid.descFromNeg    : [Result] (+1 metadata)
     range.tests.invalid.descFromPos    : [Result] (+1 metadata)
     range.tests.valid.ascFromNeg       : [Result] (+1 metadata)
     range.tests.valid.ascFromNeg2      : [Result] (+1 metadata)
     range.tests.valid.ascFromPos       : [Result] (+1 metadata)
  
     patch patch (added 1 updates)

**Comment by pchiusano** [comment]
Thanks @pete-ts! We'd like to merge this and your other PR soon, but @aryairani wanted to get to the bottom of an issue with extra namespace files being created. Sit tight for a few days.

**Comment by pete-ts** [comment]
No rush gents, do what you need to do.

**Comment by aryairani** [comment]
@pchiusano I realized in reading this that PRs that are just adding stuff (no updates) should be safe to merge.  That said, this PR does contain an patch (that was probably not meant to be published), and thus probably an update as well.

Using a combination of pull, fork, diff, and alias.many, we can probably construct what @pete-ts meant though.

I’m thinking a `pr.create` (or maybe some new command) should surface the fact that if I `add a` and then `update a`, that the closed history that I will end up pushing will contain two different `a` terms, one of which may never be noticed, and is basically junk.  Well, I guess git does this too, except you don’t necessarily commit every version of every function (and don’t necessarily publish every commit, due to squashing).

**Comment by aryairani** [comment]
In any case, something to let you stage & inspect your push a little better could be useful.

**Comment by pchiusano** [comment]
Hi @pete-ts and @anovstrup! I'm excited to merge your code into base, but first you'll need to assign a license to it (and optionally authorship info). For now until [this ticket lands](https://github.com/unisonweb/unison/issues/1129), you'll have to do it manually using the `link` command. Somewhat annoying but will get better soon.

If you pull the latest base, which now has `authors.pete_ts : Author`, `authors.anovstrup : Author`, and `licenses.pete_ts.mit_2020` (also `licenses.anovstrup.bsd3_2020` etc). Just link those to your definitions. FYI, you can link multiple things in bulk by doing a `find` and then  `link somelicense 1-23`.

For code we merge here, we prefer the MIT license, but BSD3, or BSD2 would be okay too if you had strong feelings about it.

If you encounter any issues with this, feel free to ping me on Slack or here.

**Comment by pchiusano** [comment]
Hi @pete-ts let me know if you want a hand with this, would love to get this and your other PRs merged!

**Comment by pchiusano** [comment]
Great! Merged in https://github.com/unisonweb/base/commit/097a89032bcd5375222485d3600fa884bb70c9d1
