### ISSUE TITLE
Various simple functions

### ISSUE THREAD

**Issue by emiflake** [unisonweb/base_v1#42]
The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/emiflake/unison-emi.git:.prs.base._list_functions2

  Added definitions:

     Either.mapLeft                  : (a ->{𝕖} b) -> Either a z ->{𝕖} Either b z (+1 metadata)
     Either.mapLeft.doc              : Doc (+2 metadata)
     Either.mapLeft.tests.ex1        : [Result] (+3 metadata)
     Either.mapRight                 : (a ->{𝕖} b) -> Either e a ->{𝕖} Either e b (+1 metadata)
     Either.mapRight.doc             : Doc (+2 metadata)
     Either.mapRight.tests.ex1       : [Result] (+3 metadata)
     List.lefts                      : [Either a b] -> [a] (+3 metadata)
     List.lefts.doc                  : Doc (+2 metadata)
     List.lefts.tests.ex1            : [Result] (+3 metadata)
     List.mapIndexed                 : (Nat ->{𝕖} a ->{𝕖} b) -> [a] ->{𝕖} [b] (+3 metadata)
     List.mapIndexed.doc             : Doc (+2 metadata)
     List.mapIndexed.tests.ex1       : [Result] (+3 metadata)
     List.mapIndexed.tests.ex2       : [Result] (+3 metadata)
     List.partitionEithers           : [Either a b] -> ([a], [b]) (+3 metadata)
     List.partitionEithers.doc       : Doc (+2 metadata)
     List.partitionEithers.tests.ex1 : [Result] (+3 metadata)
     List.rights                     : [Either a b] -> [b] (+3 metadata)
     List.rights.doc                 : Doc (+2 metadata)
     List.rights.tests.ex1           : [Result] (+3 metadata)
     List.singleton                  : a -> [a] (+1 metadata)
     List.singleton.doc              : Doc
     List.somes                      : [Optional a] -> [a] (+1 metadata)
     List.somes.doc                  : Doc (+2 metadata)
     List.somes.tests.ex1            : [Result] (+3 metadata)
     List.zipWith                    : (a ->{𝕖} b ->{𝕖} c)
                                     ->{𝕖} [a]
                                     ->{𝕖} [b]
                                     ->{𝕖} [c] (+3 metadata)
     List.zipWith.doc                : Doc (+2 metadata)
     List.zipWith.tests.edge1        : [Result] (+3 metadata)
     List.zipWith.tests.edge2        : [Result] (+3 metadata)
     List.zipWith.tests.edge3        : [Result] (+3 metadata)
     List.zipWith.tests.edge4        : [Result] (+3 metadata)
     List.zipWith.tests.ex1          : [Result] (+3 metadata)
     List.zipWith.tests.ex2          : [Result] (+3 metadata)
     List.zipWith.tests.zipWithRange : [Result] (+3 metadata)
     Tuple.pair                      : a -> b -> (a, b) (+3 metadata)
     Tuple.pair.doc                  : Doc (+2 metadata)

**Comment by pchiusano** [comment]
@emiflake Nice! A couple things I spotted -

It looks like your definition of `List.mapIndexed` depends on a hash `#ctggc0e1cs` that's not part of this PR. Can you do you do `view #ctggc0e1cs` and see what it comes up with, and then add that definition to the PR as well?

I think `List.zipWith` should be made tail recursive. You can pattern it after `List.zip`.

Looks like missing author + license on these definitions - 

```
 List.singleton                  : a -> [a] (+1 metadata)
 List.singleton.doc              : Doc
 List.somes                      : [Optional a] -> [a] (+1 metadata)
```

Maybe because these were originally in a different namespace without default metadata settings? Or were created before you set default metadata? Here's how we can proceed - 

* We can fix this up if you give permission to license all the definitions in the PR using the MIT license (just reply "I license all the definitions in this PR using the MIT license: https://opensource.org/licenses/MIT").
* Alternately, you can do: `link metadata.licenses.emiflake_mit_2020 List.singleton List.singleton.doc List.somes` And then do the same for `link metadata.authors.emiflake List.singleton List.singleton.doc List.somes`.

**Comment by emiflake** [comment]
@pchiusano  Thanks! I believe I have fixed those issues now. I have pushed it to the same location as the original PR, so you should be able to check it out again. I have reimplemented zipWith by consuming instead of indexing every time now, because I don't want to assume `at` has O(1) run-time cost. (It's a Data.Sequence now, right? 🙂)

**Comment by pchiusano** [comment]
Cool. Merged in Unison namespace #5csfar5avv

Using the pattern matching seems okay, though that will do some allocation as it unconses the finger tree. It is better asymptotics though. 

I'd like to standardize on conventions for the docs, but not totally sure what those should be yet, so I went with what you had. It is kind of cool that you can link tests into the docs but I found the testing stuff was a little distracting.
