### ISSUE TITLE
Add base.List.last

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#7]
This issue aims to add the `List.last` function to the unison base library.

* Quick wrapper around `List.at (List.size drop 1)`
* Example inputs added
* Evaluated outputs added
* Unit tests added
* Documentation added and linked

It's the first time I am following this process so I am not 100% sure which parts of the following you might need:

```
.petets.base> pull-request.create https://github.com/unisonweb/base https://github.com/pete-ts/base
⚙  git clone --quiet --depth 1 'https://github.com/unisonweb/base' /home/petet/.cache/unisonlanguage/gitfiles/q0rume4r1p1lc5tut0gcbbcvndjgr8ai0qst6ej9bdjr1vcgmtueo0103oi4kt4tr0m1vok5sbkk91g1qcr2og9pit3rp8ceeq752r8/HEAD
⚙  git -C /home/petet/.cache/unisonlanguage/gitfiles/q0rume4r1p1lc5tut0gcbbcvndjgr8ai0qst6ej9bdjr1vcgmtueo0103oi4kt4tr0m1vok5sbkk91g1qcr2og9pit3rp8ceeq752r8/HEAD rev-parse --git-dir
.git
⚙  git clone --quiet --depth 1 'https://github.com/pete-ts/base' /home/petet/.cache/unisonlanguage/gitfiles/cut54dgrge7sdifko04ntkptm7jl3jqlc3f9e07cd3vomjqem7g5ij0f8uij8l8f8gjrtjbcjnndj21a80ipdsolgv85cdd9iv06j58/HEAD
⚙  git -C /home/petet/.cache/unisonlanguage/gitfiles/cut54dgrge7sdifko04ntkptm7jl3jqlc3f9e07cd3vomjqem7g5ij0f8uij8l8f8gjrtjbcjnndj21a80ipdsolgv85cdd9iv06j58/HEAD rev-parse --git-dir
.git

  The changes summarized below are available for you to review, using the following
  command:
  
    pull-request.load https://github.com/unisonweb/base https://github.com/pete-ts/base
  
  Added definitions:
  
     List.last                           : [a] -> Optional a (+1 metadata)
     List.last.doc                       : Doc
     List.last.examples.elems            : [Nat]
     List.last.examples.empty            : [elem]
     List.last.examples.evaluated.elems  : Optional Nat
     List.last.examples.evaluated.empty  : Optional a
     List.last.examples.evaluated.single : Optional Nat
     List.last.examples.single           : [Nat]
     List.last.tests.elems               : [Result]
     List.last.tests.empty               : [Result]
     List.last.tests.single              : [Result]
```

**Comment by pchiusano** [comment]
Great! Merged in https://github.com/unisonweb/base/commit/08a5473913f9275097783b5d27114ad250dc8a92 and https://github.com/unisonweb/base/commit/a04b92abd82c4117840066269efb26d87666cbd3

A couple things:

* Looks like the tests maybe weren't written as watch expressions, just regular values? So while they were the correct type, they weren't being surfaced by the `test` command for me. I fixed by just doing `link metadata.isTest List.last.tests.elems List.last.empty List.last.single`.
* I ended up cherry picking these over because the current https://github.com/pete-ts/base has all your latest changes, and also looks like some definitions got accidentally duplicated at the top level (all your testing utility functions are also aliased at the top level of base, looks like). Sorry this is kind of error prone, I think we can do better.

I'm going to do a writeup of how to organize repos and multiple pull requests, but general idea is that where you would typically use branches in git, in Unison you use sub-namespaces. So your Unison codebase for contributing to base might look like

```
origin/ (a copy of current base, updated via pull)
prs.firstPr/ (a fork of origin if you're updating code)
prs.secondPr/ (new definitions, initially empty, parallel naming to origin)
```

You then push your root (including origin and prs). Then do:

```
.blah> pull-request.create https://github.com/unisonweb/base <yourrepo>:.prs.firstPr 
```

You can then easily work on multiple PRs at once, and keep them separate. Once they're merged in, you can pull the latest `base` into origin and delete (or [archive](https://github.com/unisonweb/unison/issues/1340)) the PR.
